POST http://localhost:3004/movies/ HTTP/1.1
Content-Type: application/json

{
  "directorId": 6,
  "movieName": "Jurassic Park",
  "leadActor": "Jeff Goldblum"
}


### 
GET http://localhost:3004/movies/46

### 
GET http://localhost:3004/movies

### 
PUT http://localhost:3004/movies/46 
Content-Type: application/json

{
  "directorId": 24,
  "movieName": "Thor",
  "leadActor": "Christopher Hemsworth"
} 

### 
DELETE http://localhost:3004/movies/46 HTTP/1.1

###

GET http://localhost:3004/directors HTTP/1.1 

### 
GET http://localhost:3004/directors/6/movies
