GET http://localhost:3004/states HTTP/1.1

###
GET http://localhost:3004/states/20 HTTP/1.1

### 
POST http://localhost:3004/districts HTTP/1.1
Content-Type:  application/json

{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}
### 

GET http://localhost:3004/districts/10 HTTP/1.1 

###

DELETE http://localhost:3004/districts/22  HTTP/1.1 

###

PUT http://localhost:3004/districts/10   HTTP/1.1
Content-Type: application/json

{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}

### 
GET http://localhost:3004/states/3/stats/ HTTP/1.1 

### 
GET http://localhost:3004/districts/120/details/ HTTP/1.1
